export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
    
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const registeredUserConstants = {
    GET_REGISTEREDUSERS_REQUEST: "GET_REGISTEREDUSERS_REQUEST",
    GET_REGISTEREDUSERS_SUCCESS: "GET_REGISTEREDUSERS_SUCCESS",
    GET_REGISTEREDUSERS_FAILURE: "GET_REGISTEREDUSERS_FAILURE"
}

export const grantUserConstants = {
    GRANT_USER_REQUEST: 'GRANT_USER_REQUEST',
    GRANT_USER_SUCCESS: 'GRANT_USER_SUCCESS',
    GRANT_USER_FAILURE: 'GRANT_USER_FAILURE'
}

