export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
    
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const accessFreqConstants = {
    ACCESS_FREQ_REQUEST: "ACCESS_FREQ_REQUEST",
    ACCESS_FREQ_SUCCESS: "ACCESS_FREQ_SUCCESS",
    ACCESS_FREQ_FAILURE: "ACCESS_FREQ_FAILURE"
}

export const checkAccessConstants = {
    CHECK_ACCESS_REQUEST: "CHECK_ACCESS_REQUEST",
    CHECK_ACCESS_SUCCESS: "CHECK_ACCESS_SUCCESS",
    CHECK_ACCESS_FAILURE: "CHECK_ACCESS_FAILURE"
}


